### ISSUE TITLE
Player.java一处空指针

### ISSUE THREAD

**Issue by Qrilee** [suifenge/MusicPlayerEngine#1]
在setmusiclist时，93行报空指针异常，是先getInstance获取的player实例再添加的歌单

**Comment by Qrilee** [comment]
异常信息：
 com.suifeng.lib.playerengine.core.PlayerEngineImpl.getPlayListManager()' on a null object reference
                                                                       at com.suifeng.lib.playerengine.core.Player.setPlayMusicList(Player.java:93)
                                                                       at com.qtfreet.musicuu.ui.activity.PlayMusicActivity.initPlayer(PlayMusicActivity.java:129)


使用方式：
        player = Player.getInstance(this);
        player.setFadeVolumeWhenStartOrPause(false);
        player.setPlayNextWhenError(false);
        player.setShowNotification(false);
        player.setPlaybackMode(PlaybackMode.ALL);
        player.setListener(this);
        player.acquireWifiLock();
        player.setPlayMusicList(musics);

**Comment by suifenge** [comment]
是不是没有注册Service就调用了setPlayMusicList，在没有注册PlayerService是不会初始化播放器核心的。我已经新加了判断。
